language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: anasoid
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
  - node_modules
jdk:
- oraclejdk8
script:
  - npm run coverage
  - npm run build
  - sonar-scanner
cache:
  directories:
  - '$HOME/.sonar/cache'




