language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: anasoid
    token:
      secure: bD0mmUxx/KD20p9MQDHGf6feTYY7JU5+t0e56uQ1Kdy446tkCz7YFRplFhIfICrMKGYkv5TvsJi+2M6aLg8d8DOwYYeMYy/KckU5b4vYNMT1R5Q/HlKHu57FATJynP/JbLwcDAWEHEY1wXpUz+6qRm7PSpfkOzUbKLB/sloRgzyrbi2eNbjCZj3fOqHK18vBB8u8zPsHMoWx3fDrccndj0UqnknlesNvLdhKcXvICu8Y6ys4wlt1Uogk4jhF7+R+c8zjvXVP1a4hNqYgzPYAEKeousi3jusfRfkn8YJnEMCJEf2QabEVNZPrv3fWNKwmVTjVQ+dnnagWQ6yPdAj3w5IaPT+pjsvwy9B/66a9qSnRUzrJBvDBXdZTPTLp2sFLqtcAj/kEL51Z3Ze2qC/N0k18DYnW8WrGujSIRVxikNupcveaMbd7fn3oSnX9lFp01Wh8lQVM0FBFEW3KjQzT1nK9rm88vavYB7+tWcHJBwXqLjDDALY99aKvqfup/3jrv9JXjvj0ym9aLRit0W7fVWUiBPek3aQdal+PWl5FkLKUgr3GtbZjz2txBJvwpJpA1GqhbIQeIt8ya2hZF35AFfYYW4JbmOW0Nw4EdkCe4W0RlqEAbuP4TZNSvn6aIK/7hVZ4HBn2sl2RkrCYuqaxBJQG3xy3xPGl7shDAmwsZp4=

cache:
  directories:
  - node_modules
jdk:
- oraclejdk8
script:
  - npm run coverage
  - npm run build
  - sonar-scanner -Dsonar.verbose=true -X  -v
cache:
  directories:
  - '$HOME/.sonar/cache'




