language: node_js
node_js:
  - "stable"
dist: trusty
sudo: required
addons:
  sonarcloud:
    organization: anasoid
    token:
      secure: bWpzitrWL0eJ0/0oMH9yiZkNAru5YPm9jp4bJTpjs0OXNJJEi7/oy3vdq/P3sTOHNitBkSS7OYyOQHGc2R5AYll9fmfn9HVEMutrjYgkvPVJp9yReEYDkTO+dbaTHawIJA+g8hsp6Dgk7R8PJ7LJjfEq3ww2D0fQw6gzgsZJtgyPavITiRIVCpFPFh2TR+3bF7KgipYy5vQqeoFTS7ekKpoFrd0AlMMx87j/QDiI6VrvDvQ/DF+9OuPVZx2B4BEtRpPgqI8MbHZYTwDrSLXa4/huikM/XiW4nsAGStnXHhvkopJvv+eXYQTyoqNvuDVObA1WxQTiwSd3GEsyfT9TQjtIjFZD1dLavkaIdZ+9gJXCfu2CB9LAll/8xVeeBSSAV1pRE0Gzh5ARPG+P8/VLxxCnE67iLM2tlQt48WSO3xIowTMHH3nyuaCeSozj6dxhMtR9OKGtVNs9WQdTTZ+Uf1YytWxj7nKRNGew14K45tBbByc0xj9kWwjAj2vgv7wt9PShI2mwUX2z19n0O3AOm/j+19/lqPnUry8o7DKgZc/K0oCMuujluj5LI2WSZxfTVdVtzCQXZJ64OYhnq5GqTD3g8qeMYziKf/9JqrAJfj/IK0PDbIeT95pCaWvu/Q42XFT7JjSP5mEcnmIT9PTg0/neQh+kNq+DsIFStx9ooMQ=

cache:
  directories:
  - node_modules
jdk:
- oraclejdk8
script:
  - npm run coverage
  - npm run build
  - sonar-scanner
cache:
  directories:
  - '$HOME/.sonar/cache'




